mycouchbase:
  container_name: "db"
  image: couchbase/server
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210
jboss:
  image: soonk12/jboss-eap:7-beta
  environment:
    - COUCHBASE_URI=db
  ports:
    - 8080:8080
    - 9990:9990